### ISSUE TITLE
/banner Error creating presignedurl for the banner at the moment

### ISSUE THREAD

**Issue by menonjayraj79** [srikanth-iyengar/spit-bct-bot-issue-tracker#1]
### Issue Description
/banner Error creating presignedurl for the banner at the moment

### Issue Link
https://github.com/menonjayraj79/bctproj/issues/1#issuecomment-2095195131
https://github.com/menonjayraj79/bctproj/issues/1

### Error Logs
Error creating presignedurl for the banner at the moment Err: Get "http://blockchain.spit.ac.in/public-uploads/?location=": dial tcp 172.16.10.200:80: connect: no route to host

**Comment by srikanth-iyengar** [comment]
Hopefully it will be resolved by today

**Comment by srikanth-iyengar** [comment]
Closing based on https://github.com/srikanth-iyengar/.dotfiles/issues/1#issuecomment-2112479552

**Comment by hardikg2907** [comment]
Getting the presigned URL now but, when trying to upload the png using CURL, getting 301

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
[2]+  Exit 127                X-Amz-Credential=avTBMRZzcnkAPXz11nQN%2F20240516%2Fus-east-1%2Fs3%2Faws4_request

**Comment by srikanth-iyengar** [comment]
use -L pretty standard http error codes
