### ISSUE TITLE
Error initializing the connection with Bot

### ISSUE THREAD

**Issue by Dare-marvel** [srikanth-iyengar/spit-bct-bot-issue-tracker#2]
### Issue Description
Errror establishing connection with bot

### Issue Link
[Issue](https://github.com/Dare-marvel/Aarogya-Coin-EHR/issues/5)

### Error Logs
Initiating issue for bot communication

Error establishing bot channel, error: UNIQUE constraint failed: repo_check.repo

![image](https://github.com/srikanth-iyengar/spit-bct-bot-issue-tracker/assets/104304028/8d1ed7d8-fdc8-478d-a3a5-145c45e11e9b)

**Comment by srikanth-iyengar** [comment]
> The bot will only communicate in a single issue thread. Even if the issue is closed / deleted, communication will continue in that thread. If you have closed the issue please open it again

If you have deleted the previous issue, You will have to create a new repo again
