### ISSUE TITLE
Bot not responding to /contributor

### ISSUE THREAD

**Issue by golepavan** [srikanth-iyengar/spit-bct-bot-issue-tracker#3]
### Issue Description
Bot not responding to /contributor

### Issue Link
https://github.com/pavangole/blockinsure/issues/1

### Error Logs
No error log 
![Screenshot from 2024-05-16 17-07-22](https://github.com/srikanth-iyengar/spit-bct-bot-issue-tracker/assets/64621994/058895ac-6973-4501-a1a4-4eb555e5f298)

**Comment by srikanth-iyengar** [comment]
`/contributors` you have to make a small typo, maybe I should update the help file :)
**s**

**Comment by golepavan** [comment]
The link given by the /banner and /contributors is HTTP it should be replaced by HTTPS

**Comment by srikanth-iyengar** [comment]
Don't worry that
It appears to be HTTP but after the handshake the requests get redirect to the HTTPS url :)
