### ISSUE TITLE
Checks passed and issue id is created but not approved 

### ISSUE THREAD

**Issue by Dare-marvel** [srikanth-iyengar/spit-bct-bot-issue-tracker#4]
### Issue Description
All steps performed successfully but request not approved

### Issue Link
https://github.com/Dare-marvel/Aarogya-Coin-Electronic-Health-Records-Blockchain-Mini-Project/issues/1

### Error Logs
Issue not approved yet

![image](https://github.com/srikanth-iyengar/spit-bct-bot-issue-tracker/assets/104304028/96c6d693-a40c-41ef-b9bb-661060210404)

**Comment by srikanth-iyengar** [comment]
Please be patient :)

**Comment by Dare-marvel** [comment]
How much more time do I need to wait?? It's been two days since my issue hasn't been approved

**Comment by srikanth-iyengar** [comment]
https://blockchain.spit.ac.in/projects/Dare-marvel/Aarogya-Coin-Electronic-Health-Records-Blockchain-Mini-Project

it is approved

**Comment by srikanth-iyengar** [comment]
https://blockchain.spit.ac.in/projects/Dare-marvel/Aarogya-Coin-Electronic-Health-Records-Blockchain-Mini-Project

already approved

**Comment by Dare-marvel** [comment]
Thank you for helping out
